name: Build and deploy Python app to Azure Web App - predicthub-server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: List repository contents
        run: ls -al

      - name: Verify server directory exists
        run: |
          if [ -d "./server" ]; then
            echo "Server directory exists, proceeding..."
          else
            echo "Error: ./server directory does not exist!"
            exit 1
          fi

      - name: Zip artifact for deployment
        run: |
          zip -r release.zip ./server

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_612D660D30B8429D99E4C54056F959B4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8C23D2F22AF34B43B4CEC52F5C46648A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3A9873989F434B7FA2BD4B6697E8E0F0 }}
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'predicthub-server'
          slot-name: 'Production'
          
