name: Build and deploy Python app to Azure Web App - predicthub-server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: List repository contents
        run: ls -al

      - name: Verify server directory exists
        run: |
          if [ -d "./server" ]; then
            echo "Server directory exists, proceeding..."
          else
            echo "Error: ./server directory does not exist!"
            exit 1
          fi

      - name: Zip artifact for deployment
        run: |
          zip -r release.zip ./server

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip -d extracted

      - name: List extracted files
        run: ls -al extracted

      - name: Verify server directory
        run: |
          if [ -d "./extracted/server" ]; then
            echo "Server directory exists after extraction."
          else
            echo "Error: ./server directory does not exist after extraction!"
            exit 1
          fi

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies in deployment environment
        run: |
          cd ./extracted/server
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run the application
        run: |
          cd ./extracted/server
          source venv/bin/activate
          gunicorn --bind 0.0.0.0:5000 app:app
        env:
          MONGO_URI: mongodb+srv://krishnakanta2008:krishna2008@cluster0.7rimb.mongodb.net
          CLOUDINARY_CLOUD_NAME: dtnesry4e
          CLOUDINARY_API_KEY: 764463645645659
          CLOUDINARY_API_SECRET: jFZvSGPrmYKdKV87Lff_H8YP4FE
